# Generated by Django 4.2.7 on 2024-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
