# Generated by Django 4.2.7 on 2024-08-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
