# Generated by Django 4.2.7 on 2024-08-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_products_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='email',
        ),
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
